### PR TITLE
Developper Setup Pip Missing

### PR DESCRIPTION
**Pull request by panthavma**
I added a Troubleshooting part along with what I encountered during my installation.

### CODE REVIEW

**Comment by pragma37** [comment]
I think pip is pre-installed with Blender on Windows but not on Linux.

It would be better (if possible) to actually fix the issue in the install script.

Could you try to add this:
```python
try:
    subprocess.check_call([sys.executable, '-m', 'pip', '--version'])
except:
    subprocess.check_call([sys.executable, '-m', 'ensurepip'])
```
to the top of `scripts/install_dependencies.py` and check if that works with a clean Blender installation?

Edit:
Adding `os.environ.pop("PIP_REQ_TRACKER", None)` after the ensurepip call might be needed.
https://developer.blender.org/T71856#899030

**Comment by panthavma** [comment]
This seems to work on a clean install without the PIP_REQ_Tracker call. I'll update the pull request when I'm able to (today hopefully).
I'll also update with the issue #279

**Comment by panthavma** [comment]
Alright, should be good now!

**Comment by pragma37** [comment]
Merged! I removed the change in the doc since it was incorrect. (explained in #279)

**Comment by panthavma** [comment]
Cool!

**Pull request merged**
