### PR TITLE
Allow blender addon code in malt plugin

### PR DESCRIPTION
**Pull request by Kolupsy**
added register/unregister functions to PipelinePlugin and modified MaltPipeline to update python code in pipeline plugins

### CODE REVIEW

**Comment by pragma37** [comment]
I've made a few changes to prevent some edge cases and ensure the register/unregister code always follows the same path.
Other than that it looks good.

I've only tested this with some prints, It would be good to test an actual plugin before merging.

**Comment by Kolupsy** [comment]
Thanks for reviewing. The changes look good. I can test the changes while I work on my plugin. Not sure why you took out the handler though. I found that opening a new file would disrupt the register/unregister cycle but maybe the changes that you made already took care of that. I will need to try it out...

**Comment by pragma37** [comment]
load_scene_post already calls MaltPipeline.update_pipeline.
There are many triggers for the update_pipeline function so by running everything inside it we ensure the register/unregister calls are always in sync.

load_scene_post won't call to update_pipeline if Malt is not the active renderer in the new scene, but the unregister function is guaranteed to run either on the next pipeline update or when Malt itself unregisters.

**Comment by Kolupsy** [comment]
Just noticed that the submodules werent updating, they would stay loaded on pipeline reload. I added a short snippet to also update all submodules. Not sure if that is the best way to do by name 🤔

**Comment by Kolupsy** [comment]
There are rare crashes which only ever happen when I reload the malt pipeline after editing my blendermalt plugin. It might be related to an error that sometimes can occur where malt tries to compile its node trees before the plugins have been reloaded. Its hard to replicated consistently.

[blender.crash.txt](https://github.com/bnpr/Malt/files/8667590/blender.crash.txt)
Console output on crash(below):
[malt_crash.txt](https://github.com/bnpr/Malt/files/8667631/malt_crash.txt)

**Comment by pragma37** [comment]
> Just noticed that the submodules werent updating, they would stay loaded on pipeline reload. I added a short snippet to also update all submodules. Not sure if that is the best way to do by name 🤔

I would leave this up to the plugin itself, just like Blender does.

>  It might be related to an error that sometimes can occur where malt tries to compile its node trees before the plugins have been reloaded.

You could move the setup_all_ids call after the plugins are registered.
But my experience is that reloading nodes at runtime is very prone to crashing Blender.
https://developer.blender.org/T72833
https://developer.blender.org/T81419

**Comment by Kolupsy** [comment]
> I would leave this up to the plugin itself, just like Blender does.

For the sake of consistency or is there a good reason to keep modules cached when updating? I guess maybe it saves a tiny amount of time every time you reload your plugins but I feel like you would end up repeating that code for every plugin.

> You could move the setup_all_ids call after the plugins are registered.

Yeah that fixes it. 

> But my experience is that reloading nodes at runtime is very prone to crashing Blender.

Oh yeah that one. I have been pretty lucky with that crash lately for custom eevee node development but you are totally right, that could be it. at least the crash type is the same.

**Comment by pragma37** [comment]
Module reload order can matter.
Also, it's not rare to have thousands of modules loaded, and iterating all of them can be slow.

We have to find a way to fully avoid the crashes.
Blender crashing when a developer reloads plugins is bad, but Blender crashing when users switch the renderer to Malt is a big nope.

**Comment by Kolupsy** [comment]
The way I see it now is that the crash comes from reloading modules that contain custom node data. This generally only happens when you develop because a deployed addon usually only loads the modules containing custom nodes on start and unloads them when closing blender but when integrating the addon register/unregister, this can happen at other times while using blender (e.g. switching render engine or reloading the malt pipeline). From what I read about this crash this is something that would need to be fixed in blender (has already been brought up but it seems there hasnt been anything done about it). Not sure if there is ANYTHING that we can do from a malt side apart from avoiding to reload python modules with custom nodes while using blender. Which would mean either dropping the pull request or only loading/unloading the python part of the malt plugins when the malt addon ITSELF registers/unregisters. What do you think?

**Comment by pragma37** [comment]
Registering only once means the addon must be pipeline agnostic, which I guess is ok?

**Comment by Kolupsy** [comment]
Ok so this is just an idea, I added panel below the pipeline settings panel in the world properties to update the python code of plugins and also give a location for plugins to have their own panels. Because I believe if you specify 'bl_parent_id' on a panel class you can automatically attach that panel to another existing panel as a subpanel.
image

**Comment by pragma37** [comment]
To ensure plugins are loaded after all BlenderMalt modules are ready I would just move the register/unregister calls to the main register/unregister functions in __init__.py.
Using a timer for that seems like a potential source of trouble.

About the plugin settings panel, I'm not too sold on the idea since there's no way to enforce it anyway, and users would just see an empty panel by default.

**Comment by Kolupsy** [comment]
> To ensure plugins are loaded after all BlenderMalt modules are ready I would just move the register/unregister calls to the main register/unregister functions in init.py.

That would make this case very unique though as no other single register/unregister function is being called in the register/unregister functions of `BlenderMalt.__init__.py`. But ok I guess that would work.

> About the plugin settings panel, I'm not too sold on the idea since there's no way to enforce it anyway, and users would just see an empty panel by default.

Alright yeah I can live with that, although having a reload button for plugins would be nice, especially if you setup your plugins folder without restarting blender or adding, modifying plugins at runtime. Where would you say that button could go (or maybe its just an operator callable from the F3 search)?

**Comment by Kolupsy** [comment]
Btw with the new way of managing python plugins, I have only rarely had crashes when developing and none whatsoever when using blender and malt 'normally'

**Comment by pragma37** [comment]
I think you missed [this bit](https://github.com/bnpr/Malt/blob/0278a366298477f45de7f307f56ced90b67c6c3d/BlenderMalt/__init__.py#L156), all the register functions are called from `__init__.py`. 

And yep, I think is better to leave the reload operator outside the UI.

**Comment by Kolupsy** [comment]
ok so the register and unregister functions have been moved to the `__init__.py` file. The reload operator still exists, its just never drawn in the UI anywhere. Sound good?

**Comment by pragma37** [comment]
I've rebased the pull request so it can be merged with the current Development branch.
I've also moved all the code to `__init__` and simplified the code a bit.

If you agree I'd say this is ready for merging.

**Comment by Kolupsy** [comment]
Yup tested it and it seems to work fine. I would say so too.

**Comment by pragma37** [comment]
Ok. Merged! :)

**Pull request merged**
