### PR TITLE
added shortcut for editing node trees on malt nodes

### PR DESCRIPTION
**Pull request by Kolupsy**
I personally find it very useful to edit/enter node trees from the render graph for example. This behaves like pressing TAB to edit a node tree in shader/geo/compositor nodes.
Current problems are:
1) it doesnt have that nice context path display that the builtin editors have (photoshopped in green below)
Screenshot 2022-06-08 183249
2) there is ambiguity involed because there could be multiple graphs used in one node (although I have never seen it before).

problem 1 can be fixed by manually drawing the context path display onto the screen, problem 2 could be solved by opening a popup that lets you choose from all the possible graphs to edit

What do you think?

### CODE REVIEW

**Comment by pragma37** [comment]
I like the feature. (I didn't know about SpaceNodeEditorPath!)

But I think there should be a UI-only way to use it.
Something like an edit button on the side of node tree properties.
That would also remove the ambiguity, although at the moment is actually not possible for nodes to have more than one node tree property.

**Comment by Kolupsy** [comment]
> (I didn't know about SpaceNodeEditorPath!)

me neither up until a few days ago which is why I am bringing this up just now. I always assumed you would need to do some hacky operator stuff to make that happen but turned out its rather simple actually.

> But I think there should be a UI-only way to use it

fair enough. In default blender group nodes have an operator "edit group" in their context menu and the node editor space also has a button in its header that removes an element from the path (or in other words exists a node tree that you are editing).
A button next to the node tree properties sounds good too.

What do you think about the problem 1 (and proposed solution)?

**Comment by Kolupsy** [comment]
I have added a basic button UI for editing the node tree. But it is a bit jammed in there to be honest because there is code duplication (same UI function in both the `MaltProperty` and `MaltMaterial` code) and there is currently no way to 'filter' the graph that will get edited if a node had multiple graphs to edit. I have not found a way using operator properties that would work with the way properties are being drawn in BlenderMalt. Also checks would be needed if the area type was not matching but `MaltMaterial.draw_ui` and `MaltPropertyGroup.draw_parameter` dont get any context passed

image

**Comment by pragma37** [comment]
I've updated the edit buttons to use callbacks.
I've also moved the "hairy" part of finding the node tree to MaltFunctionNode.

> What do you think about the problem 1 (and proposed solution)?

I think it's ok? I don't like it too much, but I don't think there's a better way.

**Comment by Kolupsy** [comment]
awesome, alright. I really need to understand that callback system some time. I will try to think of something for the path display (idk what to call it 😅 ). I think either its some UI thing on the header or we go through the trouble of having a peristent draw handler running on the malt tree (i have done something like that for my own custom node tree recently)

**Comment by Kolupsy** [comment]
I think it does look alright. And its not too distracting I would say
image

**Comment by pragma37** [comment]
I've updated the path rendering to match the user settings.
I've also fixed the x position (it would break when the toolbar was not hidden).

I'd say this is ready for merging?

**Comment by Kolupsy** [comment]
How did it break when the tool bar wasn't hidden? It should get offset a little when the tool bar is shown because that extra space from the tool bar could contain UI elements

**Comment by pragma37** [comment]
The draw coordinates are relative to the space, not the full area. By offsetting by the toolbar width the text ends up in the middle of the editor. (just make the test width the old version).

**Comment by Kolupsy** [comment]
Yeah I guess that works too. Alright yeah looks good. Lets merge

**Pull request merged**
