### PR TITLE
node-ux : Preview System

### PR DESCRIPTION
**Pull request by Kolupsy**
I have prototyped the preview system for Malt Trees. 

You interact with it by pressing `Shift-P` on a node. It will set the first socket as the preview socket. Repeating the shortcut will cycle through the available sockets
Pressing `P` on a node auto-connects the nodes socket(s) to the preview socket. It has the same repeating behavior. 

What do you think? (Also I used type hinting in the code, you can see how well that reads in your opinion)

image

### CODE REVIEW

**Comment by Kolupsy** [comment]
What's nice about this is that the system is ignorant of the kind of node tree that it's on so we can use it on any type of graph. Something that would be graph-specific would be the "output guessing". I think we should find a way to define this behavior in each graph type specifically

**Comment by pragma37** [comment]
Seems like a good solution! 👍 

The text drawing is not getting positioned correctly for me, though.
Recording 2022-07-26 at 23 10 06

> (Also I used type hinting in the code, you can see how well that reads in your opinion)

I still think the same as the last time.
I have to give a proper look at it before taking a decision and I don't like the idea of dropping it into the middle of Malt and crossing my fingers.

**Comment by Kolupsy** [comment]
> The text drawing is not getting positioned correctly for me, though.

Huh that is weird. Probably related to the UI scaling since the offset changes when moving the mouse. (I am telling you, everything that uses the UI scale ends up being a massive headache. Especially because I usually have it at 1 so as a factor it doesnt do anything until you change it from 1 to something else)

**Comment by Kolupsy** [comment]
I have tried to look into why its not drawing in the correct location for you but I just could not figure it out. The API is horribly designed in that area. If you could look into it yourself since you are having the issue with it, that would be great. Things like setting the UI scale to 1 to see what happens, drawing the location at which the text is drawn too ect. 

I have also considered not using the 'POST_VIEW' drawing mode but it seems that in 'POST_PIXEL' we would have the same issue

**Comment by Kolupsy** [comment]
Ok I had a look at the node wrangler source code and used their method to correct their drawing locations for all sorts of preferences. This still works great for me and I hope it now does for you as well. 
Also changed the handler to draw in "POST_PIXEL" mode for a better quality text drawing, tinted the text to reflect the socket color and gave it a little drop shadow to improve readability

**Comment by pragma37** [comment]
It's working now!

> I am telling you, everything that uses the UI scale ends up being a massive headache. Especially because I usually have it at 1 so as a factor it doesnt do anything until you change it from 1 to something else

I have the Blender UI scale at 1, but the global WIndows scaling at 125% (laptop). I guess that's were the problem came from.

**Comment by Kolupsy** [comment]
> I have the Blender UI scale at 1, but the global WIndows scaling at 125% (laptop). I guess that's were the problem came from.

Ok interesting. Anyway, glad that it works. Do you wanna merge and then keep working on it in the main branch (whats still missing is the 'guessing' and maybe some UI adjustments)?

**Comment by pragma37** [comment]
>  Do you wanna merge and then keep working on it in the main branch (whats still missing is the 'guessing' and maybe some UI adjustments)?

If by the main branch you mean the node-ux one then yes. 👍 
I think it's ok to skip the "guessing" since it's very quick to set up manually anyway.
Maybe just display a warning when you mark a socket for preview and there's no preview output active.

That said, I think we should move this kind of "non-core" functionality from MaltNodeTree to its own file (MaltNodeUITools or something like that).

**Comment by Kolupsy** [comment]
> That said, I think we should move this kind of "non-core" functionality from MaltNodeTree to its own file (MaltNodeUITools or something like that).

Ok lets do that before merging.

**Comment by Kolupsy** [comment]
So I have moved all the UI stuff to another file. It works fine at first but Malt crashes when you try to open a new file with blender already running. I checked and this doesnt happen in the `node-ux` branch. I know its some sort of import thing but I am not sure what to do about it:

image

Malt doesnt have any logic to ensure a proper class registration order since every file registers its own classes instead of registering them together in one place. So I am not sure how to make this error go away (usually this error happens because a class is trying to register when a property group referenced as a pointer or collection property is not registered yet)

**Comment by pragma37** [comment]
I can't reproduce the issue on my end, but I've removed some unnecessary cross-module dependencies. Maybe that helps?

> Malt doesnt have any logic to ensure a proper class registration order since every file registers its own classes instead of registering them together in one place.

The logic is to ensure modules are registered in the correct order. If the correct order requires mixing the order of different modules, that's a bad sign.
In this case, for example, I wouldn't register the NodeTreePreview in the MaltTree itself.

**Comment by Kolupsy** [comment]
> In this case, for example, I wouldn't register the NodeTreePreview in the MaltTree itself.

What alternative would you suggest? To me this is the only way that makes sense.

**Comment by pragma37** [comment]
You can register the property group in the bpy.type.NodeTree directly. (I guess that's how the Node Wrangler addon does it?)
That way you avoid the dependency.

**Comment by Kolupsy** [comment]
> You can register the property group in the bpy.type.NodeTree directly. (I guess that's how the Node Wrangler addon does it?)
That way you avoid the dependency.

Oh that. Yeah I guess you could do that but you would register this property to ALL node trees then which is more than we need. Making the registration routine of BlenderMalt more robust seems like a more worthwhile venture.

Anyway I tested the patch and it looks good. No more errors when loading a new file. Merge?

**Comment by pragma37** [comment]
> Oh that. Yeah I guess you could do that but you would register this property to ALL node trees then which is more than we need. Making the registration routine of BlenderMalt more robust seems like a more worthwhile venture.

I'm not sure if this means that you agree or not.
I think adding 2 extra strings and 1 int to each NodeTree is ok if that makes the module registration more robust.

**Comment by Kolupsy** [comment]
> I'm not sure if this means that you agree or not.
I think adding 2 extra strings and 1 int to each NodeTree is ok if that makes the module registration more robust.

Ah sorry that wasnt clear from me. Maybe its because I am more used to it but I prefer to pool all classes in a pool in the `register`/`unregister` functions of the entire addon where I can ensure programatically that the registration order is correct. Thay way you dont have to manually change the order of module imports at all (so this was more on a general note).

If we register the properties to the NodeTree class, where would we put the functions to handle all the logic associated with the preview system? I think it would be important to keep them close to the properties themselves since you are not supposed to set or read those properties at all and instead only interface with the provided functions for security reasons.

**Comment by Kolupsy** [comment]
Hm I think I'm getting ahead of myself. I think what I am trying to propose would be more than I even would have time for at the moment and definitely beyond the scope of a node UX update...

**Comment by pragma37** [comment]
> If we register the properties to the NodeTree class, where would we put the functions to handle all the logic associated with the preview system? 

I mentioned the 3 properties in terms of "wasted" memory for non-Malt node trees.
I didn't mean you had to declare them individually in the NodeTree class, the PropertyGroup itself is fine.


I don't think registering all classes in a single global function would scale well for something the size of Malt anyway.
Regardless, my main point is that if you have to mix the class registration order between multiple modules, that sounds like an architecture issue.

**Comment by Kolupsy** [comment]
> I didn't mean you had to declare them individually in the NodeTree class, the PropertyGroup itself is fine.

oh right, ok. Makes sense

> Regardless, my main point is that if you have to mix the class registration order between multiple modules, that sounds like an architecture issue.

I think it took me until just now to understand what you meant by that 😅

**Comment by Kolupsy** [comment]
alright so I switched it up and registered the tree preview to the NodeTree class instead. 
There is also no weird import switcheroo anymore that I had earlier.

**Comment by Kolupsy** [comment]
I dont have anything to add to this PR, is there anything you would like to change before merging?

**Comment by pragma37** [comment]
Oops! Sorry, I tested the patch and took a look at the code but forgot to comment here.

Yep, this can be merged.

**Pull request merged**
